### ISSUE TITLE
Update the Attestation Page Type list

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/floswhistle-pandemic#11]
The dropdown for roles should include:

Emergency Medical Technician
Paramedic
Registered Nurse
Advanced Practice Nurse
Licensed Practical Nurse
Certified PT Care Tech / CNA
Respiratory Therapist
Physician
Physician's Assistant

This will require both a front end and back end change.

**Comment by c-malecki** [comment]
This will be ready to go for the front end whenever. Values just need to correspond with whatever the back end requires.

**Comment by DavidEBest** [comment]
I'm updating these now. The values should be:

* emt
* paramedic
* rn
* apn
* lpn
* cna
* rt
* physician
* pa
