### ISSUE TITLE
Update the location list for reporting

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/floswhistle-pandemic#12]
The new list for reporting locations include:

Pre-Hospital
Hospital
Nursing Home /LTAC/LTCH
Free-standing ER
Urgent Care Clinic

This will need to be coordinated with the backend changes necessary to support this.

**Comment by c-malecki** [comment]
This will be ready to go for the front end whenever. Values just need to correspond with whatever the back end requires.

**Comment by DavidEBest** [comment]
@c-malecki I'll need to update the backend to support these different values. They are stored in an enumeration.

I'll get started on that, values can be:
* pre_hospital
* hospital
* nursing_home
* er
* urgent_care
