### ISSUE TITLE
Update the 'Thank You' page to match the XD mockup.

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/floswhistle-pandemic#6]
Text should be updated to match the text here:

https://xd.adobe.com/view/9a259d44-e127-46f8-6778-b0d5d4280412-ec14/screen/6c05a80c-e221-4c49-8b4a-6544d28329fe/iPhone-X-XS-11-Pro-1

**Comment by jadaw63** [comment]
I don' t have permission to push changes at this time. I have updated the thank you page.

`import React from 'react';
import { Link } from 'react-router-dom';
import './_styles.scss';

const ThankYouPage = props => {
	return (
		<div className="ThankYouPage">
			<h1>Thank You</h1>
			<p>
				Bless you for all you're doing to care for your patients and each other during this pandemic. </p>
						
				<p>Please share this project with your colleagues, and stay in touch!</p>
			
			<div className="socials">
				<a href="https://www.facebook.com/flo.nightingale.3344"><i className="fa fa-facebook-f"></i></a>
				<a href="https://twitter.com/F_NightingaleRN"><i className="fa fa-twitter"></i></a>
				<a href="https://www.instagram.com/FloNightingaleRN/"><i className="fa fa-instagram"></i></a>
			</div>

			<div className="buttons">
				<Link className="button" to="/">Go Back</Link>
			</div>
		</div>
	);
};

export default ThankYouPage;
`

**Comment by DavidEBest** [comment]
Great, thank you. I've invited you to the organization. Could you create a pull request?

**Comment by jadaw63** [comment]
> Great, thank you. I've invited you to the organization. Could you create a pull request?

A pull request was created. Thanks!
